---
title: "COMP7024: Programming for Data Science"
subtitle: "Assignment Quarter 1 2026"
author: "Harriet Nafula Wanyonyi Student ID: 22119241"
date: "2026-03-10"
output: pdf_document
---

## Project Cover Page & Declaration

By including this statement, we the authors of this work, verify that:
* We hold a copy of this assignment that we can produce if the original is lost or damaged.
* We hereby certify that no part of this assignment/product has been copied from any other student's work or from any other source except where due acknowledgement is made in the assignment.
* No part of this assignment/product has been written/produced for us by another person except where such collaboration has been authorised by the subject lecturer/tutor concerned.
* We are aware that this work may be reproduced and submitted to plagiarism detection software programs for the purpose of detecting possible plagiarism.
* We hereby certify that we have read and understand what the School of Computing, Engineering and Mathematics defines as minor and substantial breaches of misconduct.

\newpage